version: '3.11'

services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend/app:/code/app

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend/src:/app/src
      - ./frontend/public:/app/public
    depends_on:
      - backend

  notebooks:
    build: ./notebooks
    ports:
      - "9999:9999" # map port 8888 in the container to port 9999 on the machine, as it is already being used
    volumes:
      - ./notebooks:/notebooks
    depends_on:
      - backend
