version: '3.11'

services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend/app:/code/app
    depends_on:
      - db

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend/src:/app/src
      - ./frontend/public:/app/public
    depends_on:
      - backend

  db:
    image: postgres:16
    restart: always
    ports:
      - "5432:5432"
    env_file:
      - backend/.env
    volumes:
      - pgdata:/var/lib/postgresql/data # for db persistence
      - ./backend/app/db/init:/docker-entrypoint-initdb.d # on first-time initialization only, Postgres executes all .sql or .sh files inside /docker-entrypoint-initdb.d

  notebooks:
    build: ./notebooks
    ports:
      - "9999:9999"
    volumes:
      - ./notebooks:/notebooks
    depends_on:
      - backend

volumes:
  pgdata: